-- DunaStudio — tabelas no Supabase
-- Cole este arquivo inteiro em Supabase → SQL Editor → New query → Run.
-- Pode rodar de novo sem problema: só cria o que ainda não existe.
--
-- Todas as tabelas começam com "studio_" para não se misturar com outras tabelas do mesmo projeto.
-- O acesso é feito só pelo Worker (com a service role key). O RLS fica ligado e sem políticas,
-- então ninguém consegue ler ou gravar direto pelo navegador com a chave pública.

create table if not exists studio_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  role text not null default 'client' check (role in ('client', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists studio_videos (
  id bigint generated by default as identity primary key,
  storage_key uuid not null default gen_random_uuid(),
  title text not null,
  description text not null default '',
  category text not null default 'Casamentos',
  poster_key text not null default '',
  video_key text not null default '',
  -- uploading → ready (ou error)
  status text not null default 'uploading',
  duration_seconds integer not null default 0,
  max_quality text not null default '',
  orientation text not null default 'horizontal',
  size_bytes bigint not null default 0,
  owner_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists studio_albums (
  id bigint generated by default as identity primary key,
  storage_key uuid not null default gen_random_uuid(),
  title text not null,
  description text not null default '',
  category text not null default 'Casamentos',
  cover_key text not null default '',
  owner_user_id uuid references auth.users (id) on delete set null,
  guest_upload_enabled boolean not null default false,
  guest_upload_token text unique,
  created_at timestamptz not null default now()
);

create table if not exists studio_sections (
  id bigint generated by default as identity primary key,
  album_id bigint not null references studio_albums (id) on delete cascade,
  title text not null,
  description text not null default '',
  cover_key text not null default '',
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists studio_photos (
  id bigint generated by default as identity primary key,
  album_id bigint not null references studio_albums (id) on delete cascade,
  section_id bigint references studio_sections (id) on delete set null,
  photo_key text not null,
  thumb_key text not null,
  original_name text not null default '',
  size_bytes bigint not null default 0,
  position integer not null default 0,
  source text not null default 'studio',
  uploader_name text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists studio_photos_album_idx on studio_photos (album_id, position);

create table if not exists studio_comments (
  id bigint generated by default as identity primary key,
  album_id bigint not null references studio_albums (id) on delete cascade,
  photo_id bigint references studio_photos (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  author_email text not null default '',
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists studio_contracts (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  body text not null default '',
  -- [{ "title": "Cerimônia", "event_date": "14/11/2026", "items": ["2 fotógrafos"] }]
  events jsonb not null default '[]',
  status text not null default 'pending',
  signer_name text not null default '',
  signature_data_url text not null default '',
  signed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists studio_packages (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists studio_package_items (
  id bigint generated by default as identity primary key,
  package_id bigint not null references studio_packages (id) on delete cascade,
  label text not null,
  price numeric(12, 2) not null default 0,
  default_included boolean not null default true,
  position integer not null default 0
);

create table if not exists studio_orders (
  id bigint generated by default as identity primary key,
  package_id bigint references studio_packages (id) on delete set null,
  package_title text not null,
  selected_items jsonb not null default '[]',
  total numeric(12, 2) not null,
  payer_name text not null default '',
  payer_email text not null default '',
  mp_preference_id text not null default '',
  mp_payment_id text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists studio_products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  price numeric(12, 2) not null default 0,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists studio_product_orders (
  id bigint generated by default as identity primary key,
  product_id bigint references studio_products (id) on delete set null,
  product_title text not null,
  album_id bigint,
  photo_id bigint,
  quantity integer not null default 1,
  total numeric(12, 2) not null,
  payer_name text not null default '',
  payer_email text not null default '',
  mp_preference_id text not null default '',
  mp_payment_id text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists studio_testimonials (
  id bigint generated by default as identity primary key,
  owner_user_id uuid references auth.users (id) on delete set null,
  owner_email text not null default '',
  client_name text not null,
  quote text not null,
  photo_url text not null default '',
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists studio_share_links (
  id bigint generated by default as identity primary key,
  token text unique not null,
  resource_type text not null check (resource_type in ('album', 'section')),
  resource_id bigint not null,
  allow_download boolean not null default false,
  created_at timestamptz not null default now()
);

-- RLS ligado e sem políticas: só a service role (usada pelo Worker) acessa.
alter table studio_profiles enable row level security;
alter table studio_videos enable row level security;
alter table studio_albums enable row level security;
alter table studio_sections enable row level security;
alter table studio_photos enable row level security;
alter table studio_comments enable row level security;
alter table studio_contracts enable row level security;
alter table studio_packages enable row level security;
alter table studio_package_items enable row level security;
alter table studio_orders enable row level security;
alter table studio_products enable row level security;
alter table studio_product_orders enable row level security;
alter table studio_testimonials enable row level security;
alter table studio_share_links enable row level security;

-- Usada pelo Worker quando o admin libera o Studio para um e-mail que já tem conta no Supabase
create or replace function studio_find_user_id(p_email text) returns uuid
language sql security definer set search_path = public, auth as $$
  select id from auth.users where lower(email) = lower(p_email) limit 1
$$;
revoke all on function studio_find_user_id(text) from public, anon, authenticated;
grant execute on function studio_find_user_id(text) to service_role;
